version: "3.9"
services:
  back:
    build: back
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "storage"
volumes:
  storage: